apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: {{ include "vm.fullname" . }}-vmi

  {{- if .Values.vmi.annotations }}
  annotations:
    {{- toYaml .Values.vmi.annotations | nindent 4 }}
  {{- end }}

  labels:
    app: {{ include "vm.labels.app" . }}
    component: wmi
    chart: {{ include "vm.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.vmi.labels }}
    {{- toYaml .Values.vmi.labels | nindent 4 }}
    {{- end }}

spec:
  domain:

    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio

    resources:
      requests:
        memory: 64M

  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/alpine-registry-disk-demo:latest