
vm:
  enabled: true

  running: false

  extraEnv: []
  extraEnvFrom: []
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

  service:
    annotations: {}

  ldap:
    accessFilter: "(objectClass=person)"
