{{- if .Values.vm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm.fullname" . }}-vm

  {{- if .Values.vm.service.annotations }}
  annotations:
    {{- toYaml .Values.vm.service.annotations | nindent 4 }}
  {{- end }}

  labels:
    app: {{ include "vm.labels.app" . }}
    component: vm
    chart: {{ include "vm.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  selector:
    app: {{ include "vm.labels.app" . }}
    component: vmi
    release: {{ .Release.Name }}

  ports:
  - name: ssh
    port: 22
    protocol: TCP
  - name: rdp
    port: 3389
    protocol: TCP

{{- end }}