{{- if .Values.guacd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacd

  {{- if .Values.guacd.annotations }}
  annotations:
    {{- toYaml .Values.guacd.annotations | nindent 4 }}
  {{- end }}

  labels:
    app: {{ include "guacamole.labels.app" . }}
    component: guacd
    chart: {{ include "guacamole.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.guacd.labels }}
    {{- toYaml .Values.guacd.labels | nindent 4 }}
    {{- end }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ include "guacamole.labels.app" . }}
      component: guacd
      release: {{ .Release.Name }}

  template:
    metadata:

      annotations:
        {{- if .Values.guacamole.podAnnotations }}
        {{- toYaml .Values.guacamole.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.guacd.podAnnotations }}
        {{- toYaml .Values.guacd.podAnnotations | nindent 8 }}
        {{- end }}

      labels:
        app: {{ include "guacamole.labels.app" . }}
        component: guacd
        release: {{ .Release.Name }}
        {{- if .Values.guacd.podLabels }}
        {{- toYaml .Values.guacd.podLabels | nindent 8 }}
        {{- end }}

    spec:
      restartPolicy: Always

      {{- if .Values.guacd.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.guacd.image.pullSecret }}
      {{- end }}

      securityContext:
        fsGroup: 0

      containers:
        - name: guacd
          {{- include "image" (dict "image" .Values.guacd.image) | indent 10 }}

          securityContext:
            runAsUser: 1001
            runAsGroup: 0

          ports:
            - name: guacd
              containerPort: {{ .Values.guacd.port }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.guacd.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: {{ .Values.guacd.port }}
            initialDelaySeconds: 15
            periodSeconds: 20

          resources: {{ .Values.guacd.resources }}
{{- end }}
