FROM kubevirt/container-disk-v1alpha:v0.19.0

LABEL org.opencontainers.image.source=https://github.com/SwanseaUniversityMedical/DARE-Guacamole

# Copy the qemu generated disk image into the container
COPY img.qcow2 /disk/img.qcow2
