apiVersion: v2
appVersion: 1.0.3
description: Helm chart for deploying Apache Guacamole.
name: guacamole
type: application
version: 1.0.3
dependencies:
  - name: postgresql
    version: "13.4.4"
    repository: https://charts.bitnami.com/bitnami
    alias: database
    condition: database.enabled
    