apiVersion: v2
appVersion: 1.0.2
description: Helm chart for deploying Apache Guacamole.
name: guacamole
type: application
version: 1.0.2
dependencies:
  - name: postgresql
    version: "12.8.2"
    repository: https://charts.bitnami.com/bitnami
    alias: database
    condition: database.enabled
