
guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.1
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "750m"

  port: 4822

web:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole
    tag: 1.0.1
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "750m"

  port: 8080

database:
  enabled: true

  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

  auth:
    username: guacamole
    password:
    database: guacdb

  primary:
    service:
      ports:
        postgresql: 5432

    persistence:
      enabled: false