
guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.3
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "750m"

  port: 4822

web:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole
    tag: 1.0.2
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "750m"

  port: 8080

ingress:
  # Only enabled when web.enable is also true
  enabled: false

#  apiVersion: networking.k8s.io/v1
#  web:
#    annotations:
#      cert-manager.io/cluster-issuer: "ca-issuer"
#    host: guacamole.dare.serp.dk.serp.ac.uk
#    path: ""
#    ingressClassName: "nginx-hiru"
#    tls:
#      enabled: true
#      secretName: serp-dare-guacamole-dev-guacamole-tls

database:
  enabled: true

  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

  auth:
    username: guacamole
    password:
    database: guacdb

  primary:
    service:
      ports:
        postgresql: 5432

    persistence:
      enabled: false