
guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.2
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 1001

  port: 4822

guacamole:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole
    tag: 1.0.1
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 1001

  guacdHostname: guacd.guacamole.svc.cluster.local
  port: 8080
