
guacamole:

  defaultNodeSelector: {}
  defaultAffinity: {}
  defaultTolerations: []

  defaultSecurityContext:
    ## sets the filesystem owner group of files/folders in mounted volumes
    ## this does NOT give root permissions to Pods, only the "root" group
    fsGroup: 0

  extraEnv: []
  extraEnvFrom: []
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

controller:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole-controller
    tag: 1.2.2
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}

  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraEnvFrom: []
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.3
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  port: 4822

  service:
    annotations: {}

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraEnvFrom: []
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

web:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole
    tag: 1.4.2
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  port: 8080

  service:
    annotations: {}

  admins:
    - user: guacadmin
      # Generated from python by:
      #>>> from hashlib import sha256
      #>>> password_salt = bytes.fromhex(SALT)
      #>>> password_hash = sha256(PASSWORD.encode() + password_salt.hex().encode())
      #>>> password_hash.hexdigest().upper()
      password: "CA458A7D494E3BE824F5E1E175A1556C0F8EEF2C2D7DF3633BEC4A29C4411960"
      salt: "FE24ADC5E11E2B25288D1704ABE67A79E342ECC26064CE69C5B3177795A82264"

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraEnvFrom: []
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

ingress:
  # Only enabled when web.enable is also true
  enabled: false

  annotations: {}

  host:
  path:

  ingressClassName:

  tls:
    enabled: false
    secretName:

database:
  enabled: true

  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

  auth:
    username: guacamole
    password:
    database: guacdb

  primary:
    service:
      ports:
        postgresql: 5432

    initdb:
      # Config map name must be set by the deployment since helm won't let us use templates to generate it within values file...
      scriptsConfigMap:

    persistence:
      enabled: false