
guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.1
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 0

  port: 4822

guacamole:
  enabled: true

  image:
    repository: harbor.ukserp.ac.uk/dare/guacamole
    tag: 1.0.0
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 0

  guacdHostname: guacd.guacamole.svc.cluster.local
  port: 8080
