name: Release

on:
  push:
    branches:
      - main

jobs:

  ######################################################################################################################
  # Pre-Tasks 
  ######################################################################################################################

  slack:
    # Open a new PR thread on Slack for this CI run
    uses: SwanseaUniversityMedical/workflows/.github/workflows/slack-release-thread.yaml@v2.6.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  changes:
    # Detect which files have been changed on this PR's full history
    needs: slack
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes.yaml@v2.6.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      github-app-id: ${{ vars.APP_ID }}
      filters: |
        controller-container:
          - './.github/workflows/on-release.yaml'
          - 'containers/controller/**'
        guacamole-container:
          - './.github/workflows/on-release.yaml'
          - 'containers/guacamole/**'
        chart:
          - './.github/workflows/on-release.yaml'
          - 'charts/guacamole/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  ######################################################################################################################
  # Container Tasks
  ######################################################################################################################

  controller-container:
    # Build the DARE Guacamole container and push it as :rc-1.0.0
    needs:
      - slack
      - changes
    if: fromJSON(needs.changes.outputs.changes).controller-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-container.yaml@v2.6.0
    with:
      job-name: controller-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      github-app-id: ${{ vars.APP_ID }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: guacamole-controller
      release-tag-format: 'DARE-Guacamole-Controller-Container-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      build-command: |
        docker build -t $IMAGE -f containers/controller/Dockerfile containers/controller
      test-command: |
        docker run $IMAGE --help
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  guacamole-container:
    # Build the DARE Guacamole container and push it as :rc-1.0.0
    needs:
      - slack
      - changes
    if: fromJSON(needs.changes.outputs.changes).guacamole-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-container.yaml@v2.6.0
    with:
      job-name: guacamole-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      github-app-id: ${{ vars.APP_ID }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: guacamole
      release-tag-format: 'DARE-Guacamole-Container-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      build-command: |
        docker build -t $IMAGE -f containers/guacamole/Dockerfile containers/guacamole
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  ######################################################################################################################
  # Chart Tasks
  ######################################################################################################################

  chart:
    # Build the chart and push it as x.y.z-rc
    needs:
      - slack
      - changes
    if: fromJSON(needs.changes.outputs.changes).chart == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-chart.yaml@v2.6.0
    with:
      job-name: chart
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: guacamole
      release-tag-format: 'DARE-Guacamole-Helm-${version}'
      github-app-id: ${{ vars.APP_ID }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      chart: charts/**
      test-command: |
        helm template $CHART --values charts/guacamole/values.yaml
    secrets:
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  ######################################################################################################################
  # Post-Tasks
  ######################################################################################################################

  slack-update:
    # Update the original Slack message with the final workflow status
    # WARNING! ALL UPSTREAM JOBS MUST BE DECLARED HERE TO REPORT FAILURES CORRECTLY!
    needs:
      - slack
      - changes
      - controller-container
      - guacamole-container
      - chart
    uses: SwanseaUniversityMedical/workflows/.github/workflows/slack-release-thread.yaml@v2.6.0
    if: always()
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      status: ${{ contains(join(needs.*.result, ','), 'failure') && ':no_entry:' || ':white_check_mark:' }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
      
