name: Add to Project
on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

permissions:
  repository-projects: write

jobs:
  project:
    runs-on: 
      group: light

    steps:
    - name: add issue or pr to project
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/SwanseaUniversityMedical/projects/6
        github-token: ${{ env.GITHUB_TOKEN }}
