{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-web

  {{- if .Values.web.annotations }}
  annotations:
    {{- toYaml .Values.web.annotations | nindent 4 }}
  {{- end }}

  labels:
    app: {{ include "guacamole.labels.app" . }}
    component: web
    chart: {{ include "guacamole.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.web.labels }}
    {{- toYaml .Values.web.labels | nindent 4 }}
    {{- end }}

spec:
  selector:
    app: {{ include "guacamole.labels.app" . }}
    component: web
    release: {{ .Release.Name }}

  ports:
  - name: web
    port: {{ .Values.web.port }}
    protocol: TCP
{{- end }}